# Generated by Django 3.0.8 on 2020-07-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('name', models.CharField(help_text='City', max_length=10, verbose_name='Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('name', models.CharField(help_text='Department', max_length=10, verbose_name='Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('name', models.CharField(help_text='Enterprise', max_length=10, verbose_name='Enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('name', models.CharField(help_text='State', max_length=10, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='unit',
        ),
        migrations.AddField(
            model_name='employee',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Enterprise', verbose_name='Enterprise'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.City', verbose_name='Enterprise'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Department', verbose_name='Enterprise'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.State', verbose_name='Enterprise'),
        ),
    ]
