# Generated by Django 3.0.8 on 2020-07-11 18:19

from django.db import migrations, models
import django.db.models.deletion
import health.models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200711_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='City', max_length=10, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_name',
            field=models.CharField(help_text='name', max_length=350, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.State', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='Hrecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=35, verbose_name='Name')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('uuid', models.UUIDField(default=health.models.generateUUID, editable=False, unique=True)),
                ('date', models.DateField(null=True)),
                ('date_test', models.DateField(null=True)),
                ('result', models.CharField(help_text='result', max_length=350, verbose_name='result')),
                ('date_result', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Employee', verbose_name='Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
