# Generated by Django 3.0.8 on 2020-07-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200711_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrecords',
            options={'ordering': ['date']},
        ),
    ]
