# Generated by Django 3.0.8 on 2020-07-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20200711_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciie10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=35, verbose_name='Name')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=35, verbose_name='Name')),
                ('date_activity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('reason', models.CharField(max_length=100)),
                ('ini_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('observation', models.CharField(max_length=300)),
                ('ciie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Ciie10', verbose_name='Cie10')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Employee', verbose_name='Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
