# Generated by Django 3.0.8 on 2020-07-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_absence_ciie10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ciie10',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hrecords',
            name='name',
        ),
    ]
