# Generated by Django 2.1.1 on 2019-03-06 01:55

from django.db import migrations, models
import django.db.models.deletion
import simplecrud.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=35, verbose_name='Name')),
                ('date_actvity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('email', models.EmailField(default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=35, verbose_name='Name')),
                ('date_actvity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('manager', models.TextField(help_text='Description of manager', max_length=35, verbose_name='manager name')),
                ('total_supply', models.PositiveIntegerField(default=0, help_text='insert total supply', max_length=6, verbose_name='supplies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=35, verbose_name='Name')),
                ('date_actvity', models.DateTimeField(auto_now=True, verbose_name='Activity')),
                ('uuid', models.UUIDField(default=simplecrud.models.generateUUID, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='insert quntity', max_length=4, verbose_name='quantityy')),
                ('price', models.PositiveIntegerField(default=0, help_text='insert price', max_length=4, verbose_name='pricee')),
                ('descrption', models.TextField(help_text='Description of product', max_length=400, verbose_name='descriptionn')),
                ('date_registres', models.DateTimeField(auto_now_add=True, verbose_name='date of registry')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LOCASION', to='simplecrud.Location', verbose_name='localization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='prod_own',
            field=models.ForeignKey(db_column='uuid', on_delete=django.db.models.deletion.CASCADE, to='simplecrud.Product', to_field='uuid', verbose_name='Producto Adquirido'),
        ),
    ]
