# Generated by Django 2.1.1 on 2019-03-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0002_auto_20190306_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
