# Generated by Django 2.1.1 on 2019-03-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0003_auto_20190318_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrption',
            new_name='description',
        ),
    ]
