# Generated by Django 2.2.1 on 2019-05-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0004_auto_20190320_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
