# Generated by Django 2.2.1 on 2019-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0005_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
