# Generated by Django 2.2.1 on 2019-06-17 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0006_auto_20190605_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='location',
            name='total_supply',
            field=models.PositiveIntegerField(default=0, help_text='insert total supply', validators=[django.core.validators.MinValueValidator(0)], verbose_name='supplies'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='insert price', validators=[django.core.validators.MinValueValidator(0)], verbose_name='pricee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='insert quntity', validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantityy'),
        ),
    ]
