# Generated by Django 2.2.1 on 2019-06-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0007_auto_20190617_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_actvity',
            new_name='date_activity',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='date_actvity',
            new_name='date_activity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_actvity',
            new_name='date_activity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_registres',
            new_name='date_register',
        ),
    ]
