# Generated by Django 3.0.3 on 2020-06-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0008_auto_20190618_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deploy_date',
            field=models.DateTimeField(null=True),
        ),
    ]
