# Generated by Django 3.0.3 on 2020-06-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0009_product_deploy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deploy_date',
            field=models.DateField(null=True),
        ),
    ]
