# Generated by Django 3.0.3 on 2020-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0011_auto_20200621_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='observation',
            field=models.TextField(help_text='Description of product', max_length=100, null=True, verbose_name='observationn'),
        ),
    ]
