# Generated by Django 3.0.3 on 2020-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0012_product_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='observation',
            field=models.TextField(help_text='Descripn of product', max_length=100, null=True, verbose_name='observationn'),
        ),
    ]
